### ISSUE TITLE
Love it, just wish it could be non-sectioned with a prop

### ISSUE THREAD

**Issue by hammadzz** [renrizzolo/react-native-sectioned-multi-select#1]
I wish it already did, if I have time I may fork and implement this feature. But it maybe faster for the author to do it. Seems minor but looking at the codebase there is a lot there to digest.

**Comment by renrizzolo** [comment]
hey @hammadzz , this just renders a `<FlatList>` with the supplied data. 
If one of the rows has the `subKey` children, a FlatList is rendered inside that row with the children. 

In other words, there are no 'sections' if your items don't have children, so I don't see the need for a prop.

Or am I misunderstanding what you want it to do?

Thanks!

**Comment by hammadzz** [comment]
@renrizzolo So I can have a list of items with no sections at all? How would I do that? I did try. I tried a simple JSON array with objects with id and name. I may come back and try it again, for now I just split my items into sections.

**Comment by renrizzolo** [comment]
That's correct. 
Maybe it's how the parent items are styled by default that's throwing you off? 
For example to have the parent items styled like the sub items, you can do something like this:
```
styles={{
  separator: {
    height: 0,
  },
}}
itemFontFamily="light"
```

And if this was your array of items...
```
const items = [
  {
    name: "Apple",
    id: 1,
  },
  {
    name: "Strawberry",
    id: 2,
  },
  {
    name: "Pineapple",
    id: 3,
  },
  {
    name: "Banana",
    id: 4,
  },
  {
    name: "Watermelon",
    id: 5,
  },
]
```
...It would look like this: 

![screen shot 2017-11-29 at 10 00 08 am](https://user-images.githubusercontent.com/13904763/33348996-6cadc43a-d4ec-11e7-8c50-c112e1c39360.png)

Maybe it's not that intuitive because I designed it with parent/child items in mind.

**Comment by hammadzz** [comment]
Definitely the styles that threw me off! That solves it!
