### ISSUE TITLE
[Android]: fontFamily not working for items/subitems

### ISSUE THREAD

**Issue by skizzo** [renrizzolo/react-native-sectioned-multi-select#131]
Hi,

I noticed that when defining `fontFamily` in the `styles` property of the `SectionedMultiSelect` component, it only gets respected on iOS and not on Android. It's important to note that in all other parts of the app, using the font works well.

This can be reproduced by adding a custom font (in my example, `MyCustomFont`) to the app, and then `styles` object looks like this:

```
<SectionedMultiSelect
  {...otherProps}
  styles={{
    itemText: {
      fontFamily: "MyCustomFont", // ignored on Android
    },
    subItemText: {
      fontFamily: "MyCustomFont", // ignored on Android
    },
    selectedSubItemText: {
      fontFamily: "MyCustomFont", // ignored on Android
    },
    searchTextFontFamily: "MyCustomFont", // ignored on Android
  }}
  />

```

Any ideas why this might be happening?

**Comment by skizzo** [comment]
Anybody?

**Comment by scabezasiq** [comment]
The same thing happened to me.

Try with:

`<SectionedMultiSelect
  {...otherProps}
  itemFontFamily={{
    fontFamily: "MyCustomFont",
  }}
  subItemFontFamily={{
    fontFamily: "MyCustomFont",
  }}
  styles={{}}
  />`

**Comment by geiz** [comment]
I had this issue earlier. It happens when you use "fontWeight". For some reason anything that is not `fontWeight: 'normal'` will not show up properly on some android devices.

Solution: Remove fontWeight from your css here. Load the bold/italic/light versions of your font directly into your app instead to get the style you want.
