### ISSUE TITLE
There is a confusion if unique key of main item equal with unique key of sub items

### ISSUE THREAD

**Issue by d-dustintruong** [renrizzolo/react-native-sectioned-multi-select#33]
If the data array is:
`
const items = [
  {  
    name: "Fruits",
    id: 0,
    children: [{
        name: "Apple",
        id: 10,
      },{
        name: "Strawberry",
        id: 17,
      },{
        name: "Pineapple",
        id: 13,
      },{
        name: "Banana",
        id: 14,
      },{
        name: "Watermelon",
        id: 15,
      },{
        name: "Kiwi fruit",
        id: 16,
      }]
  },
  {
    name: "Gems",
    id: 1,
    children: [{
        name: "Quartz",
        id: 1,
      },{
        name: "Zircon",
        id: 21,
      },{
        name: "Sapphire",
        id: 22,
      },{
        name: "Topaz",
        id: 23,
      }]
  }
]`

When we set the selectedItems array is [1] with readOnlyHeadings = true, it will check the Gems instead of Quartz. Please fix it. Thanks!

**Comment by renrizzolo** [comment]
@tdduy-us all your ids must be unique.

**Comment by d-dustintruong** [comment]
Hi Ren,

If we have a data array from database with 2 tables are departments and
employees, the ids cannot be unique. I think we should have a key for sub
item. Thanks!

[
        {
            "id": 1,
            "name": "IT department ",
            "department_employee": [
                {
                    "user_id": 136,
                    "name": " Employee A"
                },
                {
                    "user_id": 141,
                    "name": "Employee B"
                }
            ]
        },
        {
            "id": 2,
            "name": "HR department",
            "department_employee": [
                {
                    "user_id": 1,
                    "name": " Employee C"
                },
                {
                    "user_id": 121,
                    "name": "Employee D"
                }
            ]
        },
    ],

**Comment by renrizzolo** [comment]
@tdduy-us I do see what you're saying, but I don't think the data you put in should be mutated.
You would put in `user_id: 1` and receive `user_id: 'my_sub_key_1'`, right? how are you going to deal with that ID that doesn't represent what's in your db (The obvious answer is you strip off the sub key).

I'm not opposed to an optional prop for it, just don't feel the library is responsible for this The selected id's is a flat array anyway.

**Comment by Jeremy-coding** [comment]
@renrizzolo  how hard is it to change so that selected Ids returns a 2d array?  I have the same requirements as @tdduy-us , Each of my major items has its own collection of subitems from a different database table, and I want the saved id values to reflect that.

When I was first reading the docs, I was surprised I wasn't able to set subKeyUniqueKey and subKeyDisplayKey independently of uniqueKey and DisplayKey. It makes sense that for a sectioned multi-select the response should be a 2d array rather than a flat array (or at least there should be an option for that).

Thanks for all your work on the library, it's really useful.

Edit: I had a look at the code, and I can maybe make these modifications myself and submit them as a pull-request, but if you'd rather do it in the way that makes sense to you then I can leave that to you.

For my purposes, it would be enough to tag the Items with a [1, uniqueKey] while the subitems get tagged with a [2, uniqueKey], but that's probably not the best implementation since every Item should be able to have its own set of subitems, and not rely on each item having subitems of the same type.

Slightly better than that would be modifying SelectedItems to return a 2d array like this: [[uniqueKeys of Items], [uniqueKeys of Subitems]].

The best implementation is SelectedItems returns an array where each Item is itself an array, containing the Item id, a boolean for the item's selected status, and an array of its selected subItem ids. Like this: SelectedItems = [ [Item1 id, Item1selected=true/false, [Item1Subitem ids]], [Item2 id, Item2selected=true/false, [Item2SubItem ids]], ... ]

**Comment by renrizzolo** [comment]
I agree. I don't know why it's flat, I probably just had tunnel vision for my particular use.
 
There is already a function to return the original objects.
https://github.com/renrizzolo/react-native-sectioned-multi-select/blob/6b50a9fbc3b3fcd6080354e7d4baae498c991257/lib/sectioned-multi-select.js#L583-L594

Would it be helpful to add parentId to the sub items in that array? it's still a flat array of selected item objects, but this would at least allow you to determine which are sub items.

Not really sure how best to address clashing ids for parent / sub item. Looks like a lot of code would need to be updated..

Probably splitting it into 2 would be the simplest (`selectedItems[0]` is parent ids, `selectedItems[1]` is sub ids).
