### ISSUE TITLE
How to select all Child Item when Parent Click without taking the Parent Item?

### ISSUE THREAD

**Issue by phalonX** [renrizzolo/react-native-sectioned-multi-select#50]

**Comment by renrizzolo** [comment]
I can't see a way for this to be done with the current implementation.
If you were to select a parent, then remove that id from the selected items, there's no way to know that the parent is selected, so you won't be able to deselect it.

One thing you can do, is use `onSelectedItemObjectsChange`, because that doesn't affect the component's idea of what is selected.

```js
  onSelectedItemObjectsChange = (selectedItemObjects) => {
    const filtered = selectedItemObjects.filter(val => !val[subKey]) // if the object has children we know it's a parent item
    this.setState({ selectedItemObjects: filtered })
  }
```

unfortunately the parent item will still display as selected.

**Comment by phalonX** [comment]
i do a little modified to get the parent id when they were chosen at `_toggleItem `function and then i filtered all `selectedItems `at `_displaySelectedItems `function to exclude the parent ID from `selectedItems `and then add new function to give all the parent ID to parent component so i can exclude it again at parent component in `onSelectedItemsChange `function where i set the item state on parent component

Now Can I set default value in the `SectionedMultiSelect`? i want to make default value in `SectionedMultiSelect` with child value... Can you help me explain how to do so?

**Comment by renrizzolo** [comment]
You want a default selected value? Just add its ID to your items array when you initialize it/ when the component mounts.
