### ISSUE TITLE
Select all items in section

### ISSUE THREAD

**Issue by YoucefMami** [renrizzolo/react-native-sectioned-multi-select#6]
Hi,

Thanks very much for the package. Very useful! I was wondering if there was any way to give the option to select all items in a given section? For long lists, selecting items one by one could be cumbersome.

I checked the current props and you could add an extra property (say selectSubItems) to use in combination with readOnlyHeadings=false. If selectSubItems is true in combination with readOnlyHeadings=false, then selecting the parent item should cause all sub items to be selected as well.

In combination with that enhancement, I think it would be nice not to list all sub items within a given category when selecting an entire category. Instead, the category should be listed as would happen currently if using readOnlyHeadings=false or "All of CategoryName" to make it explicit. 

Please let me know your thoughts.

Thanks

**Comment by renrizzolo** [comment]
Hi @YoucefMami, That sounds doable. 

In my own integration I'd only want it to be a cosmetic change, because if the parent category is selected, the sub categories are by default contained in the results.

Would you want to have the parent id and all children ids broadcast to the `selectedItems` state?

I'm not sure I follow the last paragraph. Do you mean not display sub items at all?

**Comment by YoucefMami** [comment]
Hi @renrizzolo, your point makes perfect sense. I am mostly suggesting the change for user-friendliness. If I am selecting a parent category, intuitively, I expect all sub-categories to be selected as well but.

That does not need to be reflected in the selectedItems state, necessarily. The selectedItems state can simply contain the parent id when the parent category is selected. 

Regarding the last paragraph, yes I was suggesting tagging a parent category selection by "All of that category" rather than simply the category name (or anything more explicit), to make it clear to the end user what the parent category selection implied.

Lastly, I wanted to pick up your brain on ids. I get mine from a database where parents and children are stored in two different tables. This means that if I select a parent category with id x, and I have somewhere a child with the same id (it might not even be in that category), then the child would get selected as well and vice-versa. Is there any way to treat parent ids and children ids differently?

Thank you!

**Comment by renrizzolo** [comment]
Hi @YoucefMami, please have a look at the dev branch. I have added selectChildren and highlightChildren props.

`selectChildren={true}` will select _and_ broadcast to the state all the children of the selected parent.
`highlightChildren={true}` will tick the children but only broadcast the parent id. 

HighlightChildren is a little bit buggy in that if you press a parent then try to unhighlight a child item it won't do anything (actually it will add and remove that child id but stay highlighted). Whilst I could add a new function to make that work (visually), it doesn't make sense because all the children should be highlighted anyway...

If you wouldn't mind testing it out, let me know how it works ok for you and if you have any suggestions.

Fwiw I added custom icon component props and a `selectedItem` style which allows you to do e.g a background color for selected items.

Re: ids, Is there a way you can add something to the ids before you pass the items in to the component?
 you could use a template string like \``${id}-${parent ? 'parent' : 'child'}`\`

**Comment by YoucefMami** [comment]
Hi @renrizzolo, sorry for the late reply. Thank you for the additional properties. I just got a chance to conduct some quick testing and I think I may have spotted an inconsistency. 
I tried:
`selectChildren={false}`
`highlightChildren={true}`

I am expecting the children to be ticked but they don't seem to be. The ids broadcasted are as expected.

Regarding ids, I am now making them unique by adding a string to the parent id.

**Comment by renrizzolo** [comment]
@YoucefMami 
With those settings the children will be highlighted and the parent's id will be broadcasted.
The checkmark of the children will be `colors.disabled`, to reflect that you can't edit the children as only the parent is used in this case. Maybe the disabled colour is the same as your label background or something?
