### ISSUE TITLE
Show only the searched list items

### ISSUE THREAD

**Issue by auzair92** [renrizzolo/react-native-sectioned-multi-select#61]
Hi! Thank you for this component, it's really neat and extremely customizable.

I have a couple of questions regarding it:

1. Is there a way to disable rendering the list and only show the items that user has searched for? My list is quite long and I do not want to show all items when it loads, but only the items that are relevant to user's search query.
2. How can I show the selection checkmark icon right next to the list element? Currently, it is shown all the way to the right end of the modal. I want to show it right next to the item that has been selected.

**Comment by renrizzolo** [comment]
1. No. You may be able to do it with a custom `filterItems` function. You'd have to start with empty `items` and set the items when the search text changes. Can't imagine it'd work how you want it to though. What you're asking is more like an autocomplete, whereas this is just a filter.
2. these styles should do that:

 ```javascript
          styles={{
            itemText: {
              flex: 0,
            },
            subItemText: {
              flex: 0,
            },
          }}
```
because the checkmark would be hidden if the text is as wide or wider than the container, you might want to add something like
```
            selectedItemText: {
              maxWidth: '95%',
            },
            selectedSubItemText: {
              maxWidth: '95%',
            },
```

**Comment by auzair92** [comment]
Thanks for the response!

The styling thing (No. 2 above) is resolved. Now I am just trying to figure out how to go about solving No. 1. You're right, it does sound like auto-complete. I really liked the chips container of this component, that's the reason I went with it. I guess I'd have to combine two different components for what I am trying to achieve here: an auto-complete input component for search, and the chips part of this component.
