### ISSUE TITLE
selectedIconComponent won't show if SectionedMultiSelect is in other component

### ISSUE THREAD

**Issue by MomoHsieh** [renrizzolo/react-native-sectioned-multi-select#77]
Dear renrizzolo,
I have a question about using this lib if I put `SectionedMultiSelect` in other component. 
Icon `check` in `RowSubItem` will not render automatically.
Here is my code, first is normal use in `<view>` tag
```
<View>
    <Text>廠牌選車</Text>
          <SectionedMultiSelect
            items={this.state.carData}
            uniqueKey='id'
            icon='LogoImg'
            subKey='children'
            selectText='請選擇'
            showDropDowns
            readOnlyHeadings
            showRemoveAll
            expandDropDowns
            onSelectedItemsChange={this.onSelectedBrandChange}
            selectedItems={this.state.selectedBrandID}
          />
</View>
```
![ezgif com-resize](https://user-images.githubusercontent.com/16541945/49329185-5264f080-f5b6-11e8-8710-32b89a80da1e.gif)

second is use in `<DialogContent>` tag
```
<Dialog
        dialogTitle={<DialogTitle textStyle={{ fontSize: 20, fontWeight: 'bold' }} title={title} />}
        visible={this.state[visibleState]}
        dialogAnimation={
          new ScaleAnimation({
            toValue: 0,
            useNativeDriver: true
          })
        }
        onTouchOutside={() => {
          this.setState({ [visibleState]: false })
        }}
        overlayOpacity={0.5}
        width={0.9}
        actions={[
          <DialogButton
            key='cancel'
            text='取消'
            onPress={() => {
              this.setState({ [visibleState]: false })
            }}
          />,
          <DialogButton
            key='done'
            text='確定'
            onPress={() => {
              this.setState({ [visibleState]: false })
              this._searchResult()
            }}
          />
        ]}
      >
        <DialogContent>
          <View>
            <Text>廠牌選車</Text>
            <SectionedMultiSelect
              items={this.state.carData}
              uniqueKey='id'
              icon='LogoImg'
              subKey='children'
              selectText='請選擇'
              showDropDowns
              readOnlyHeadings
              showRemoveAll
              expandDropDowns
              onSelectedItemsChange={this.onSelectedBrandChange}
              selectedItems={this.state.selectedBrandID}
            />
          </View>
        </DialogContent>
      </Dialog>
```
![ezgif com-resize 1](https://user-images.githubusercontent.com/16541945/49329293-4ded0780-f5b7-11e8-8cf2-d4b7afc218e2.gif)

Is there any solution?

**Comment by renrizzolo** [comment]
Hi @MomoHsieh, that Dialog component doesn't use a standard render function, so it's conflicting with the way `react-native-sectioned-multi-select` uses `shouldComponentUpdate` to know when to re-render.

I only see two ways to fix your issue:

in `RowItem.js` make `shouldComponentUpdate` less strict (will result in more unnecessary re-renders but if your list is short or has few parent items, it shouldn't impact performance at all).
You want to change
```
       if (this.state.subToggled !== nextState.subToggled) {
         return true
       }
```
to 
```
      if (nextState.subToggled !== null) {
        return true
      }
``` 

the other way would be to use the `Dialog` component that the default `PopupDialog` imports. `PopupDialog` uses `react-native-general-siblings` to render the dialog adjacent to the rest of the app's jsx. I think the way it renders/updates this is the root of the problem.

try `import { Dialog, ScaleAnimation, DialogButton, DialogTitle, DialogContent } from 'react-native-popup-dialog'`
instead of 
`import Dialog, { ScaleAnimation, DialogButton, DialogTitle, DialogContent } from 'react-native-popup-dialog'` 

Hope this helps!

**Comment by MomoHsieh** [comment]
Dear @renrizzolo, thanks your solutions and both are worked but the second way 'Dialog' component has some other display issue. I will use first one! Thanks again.
